apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktor-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ktor-app
  template:
    metadata:
      labels:
        app: ktor-app
    spec:
      containers:
        - name: ktor-app
          image: gangulwar/ktor-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
