name: Docker Build and Deploy

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # DockerHub username
          password: ${{ secrets.DOCKERHUB_TOKEN }}     # DockerHub token

      # Step 3: Build and Push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true  # Push the image after building
          tags: gangulwar/ktor-app:latest  # Your DockerHub image name

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Checkout code again for deploy
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: SSH into EC2 instance to pull the image and deploy
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_IP }}          # EC2 public IP address
          username: ${{ secrets.EC2_USER }}    # EC2 SSH user (ec2-user or ubuntu)
          key: ${{ secrets.EC2_KEY }}          # Base64-encoded EC2 private key
          script: |
            docker pull gangulwar/ktor-app:latest  # Pull the latest image from DockerHub
            docker stop ktor-app || true           # Stop any existing container
            docker rm ktor-app || true             # Remove the old container
            docker run -d -p 8080:8080 --name ktor-app gangulwar/ktor-app:latest  # Run the new container
